### PR TITLE
Include quattor-ant.xml in jar file

### LINKED ISSUE #12: maven doesn't include quattor-ant.xml in the jar file
Without this, the tasks cannot be used.

### PR DESCRIPTION
**Pull request by jrha**
Fixes #12, seems to build correctly but not exhaustively tested.

### CODE REVIEW

**Comment by jrha** [comment]
Generated jar now works correctly in our SCDB.

**Comment by jouvin** [comment]
LGTM. I'd suggest to bump the release number to 10.0-SNAPSHOT to reflect the change in the tool used to build the jar. Or at least 9.1.

**Comment by jrha** [comment]
@jouvin: done.

**Comment by jouvin** [comment]
Tested successfully at LAL too. Thanks for the fix.

**Pull request merged**
